{{ if eq .Values.portalScope "cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "litmus-portal.fullname" . }}-server
  labels:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-server
    {{- include "litmus-portal.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: [ "deployments" ]
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources: [ "services", "nodes", "pods/log"]
    verbs: [ "get", "watch" ]
  - apiGroups: [ "extensions"]
    resources: [ "ingresses" ]
    verbs: ["get" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ] 
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get"]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "create" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "rolebindings", "roles", "clusterrolebindings", "clusterroles" ]
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/exec" ]
    verbs: [
      "create",
      "get",
      "list",
      "watch",
      "update",
      "patch",
      "delete",
    ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims" ]
    verbs: [ "create", "delete" ]
  - apiGroups:  [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "argoproj.io" ]
    resources: [ "cronworkflows", "cronworkflows/finalizers" ]
    verbs: [
      "get",
      "list",
      "watch",
      "update",
      "patch",
      "delete",
    ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "patch" ]
  - apiGroups: [ "policy" ]
    resources: [ "poddisruptionbudgets" ]
    verbs:  [ "create", "get", "delete" ]
  - apiGroups: [""]
    resources: ["replicationcontrollers", "secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["apps.openshift.io"]
    resources: ["deploymentconfigs"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "deletecollection"]
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods", "configmaps", "events", "services"]
    verbs:
      [
        "get",
        "create",
        "update",
        "patch",
        "delete",
        "list",
        "watch",
        "deletecollection",
      ]
  - apiGroups:
      [
          "",
          "apps",
          "batch",
          "extensions",
          "litmuschaos.io",
          "openebs.io",
          "storage.k8s.io",
      ]
    resources:
      [
          "chaosengines",
          "chaosexperiments",
          "chaosresults",
          "cstorpools",
          "cstorvolumereplicas",
          "configmaps",
          "secrets",
          "pods",
          "pods/exec",
          "pods/log",
          "pods/eviction",
          "jobs",
          "replicasets",
          "deployments",
          "daemonsets",
          "statefulsets",
          "persistentvolumeclaims",
          "persistentvolumes",
          "storageclasses",
          "services",
          "events",
          "chaosschedules"
      ]
    verbs: ["create", "delete", "get", "list", "patch", "update", "deletecollection", "watch"]
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods/log"]
    verbs: ["get", "list", "patch", "update", "watch", "create"]
  - apiGroups: [ "argoproj.io" ]
    resources: [ 
      "workflows",
      "cronworkflows",
      "cronworkflows/finalizers",
      "workflows/finalizers",
      "workflowtemplates",
      "workflowtemplates/finalizers",
      "clusterworkflowtemplates",
      "clusterworkflowtemplates/finalizers",
      "rollouts",
    ]
    verbs: [
      "get",
      "list",
      "watch",
      "update",
      "patch",
      "delete",
      "create",
    ]
  - apiGroups: [""] 
    resources: ["daemonsets", "deployments", "statefulsets"]
    verbs: ["watch"]
  - apiGroups: ["apps"]
    resources: ["configmaps", "daemonsets", "deployments", "pods", "statefulsets"]
    verbs: ["watch"]
  - apiGroups: ["eventtracker.litmuschaos.io"]
    resources: ["eventtrackerpolicies", "eventtrackerpolicies/status"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["extensions"]
    resources: ["configmaps", "daemonsets", "deployments", "pods", "statefulsets"]
    verbs: ["watch"]
{{ end }}